name: CD Deploy (Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sample-ci-cd:latest .

      # Push Image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sample-ci-cd:latest

      # Deploy to Server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/sample-ci-cd

            echo "Pulling latest Docker image..."
            docker pull ghcr.io/${{ github.repository_owner }}/sample-ci-cd:latest

            echo "Restarting container..."
            docker compose down
            docker compose up -d --force-recreate

            echo "Deployment completed!"
